### ISSUE TITLE
Text off bottom of slides

### ISSUE THREAD

**Issue by schloerke** [rstudio-conf-2020/applied-ml#3]
These slides have problematic text running off the bottom of the slide...

- [ ] P5: While We Wait, Can I Interest You in Parallelism?
- [ ] P5: Running in Parallel with {tune}
- [ ] P5: MARS in via {parsnip} and {tune}
- [ ] P5: Example of Logging
- [ ] P6: Class Prediction Metrics
  * Column 2
- [ ] P6: Changing the Probability Threshold
  * Column 1
- [ ] P6: Feature hashing
  * Column 2
- [ ] P6: Growing phase
  * Image labels are below slide line

**Comment by topepo** [comment]
I think that we got them all. Thanks
